name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install iOS 18.2 Simulator
        run: |
          echo "Installing iOS 18.2 Simulator..."
          sudo xcode-select --switch /Applications/Xcode_16.2.app/Contents/Developer
          sudo xcodebuild -runFirstLaunch
          
          # Download specific platform (iOS 18.2)
          sudo xcodebuild -downloadPlatform iOS

      - name: Debug Available Simulators
        run: |
          echo "Available iOS Simulators:"
          xcrun xctrace list devices 2>&1 | grep -E 'iPhone.*\([0-9.]+.*\)'

      - name: Select iPhone 16 Pro Simulator (18.2)
        run: |
          # Explicitly select the iPhone 16 Pro Simulator with OS 18.2
          device=$(xcrun xctrace list devices 2>&1 | grep "iPhone 16 Pro.*18.2" | head -1 | sed -E 's/ *\([^)]*\)//g')
          if [[ -z "$device" ]]; then
            echo "Error: No available iPhone simulators found!"
            exit 1
          fi
          echo "Selected Simulator: $device"
          echo "SIMULATOR_DEVICE=$device" >> $GITHUB_ENV

      - name: Set Default Scheme
        working-directory: ios-assignment
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]" || echo "")

          if [[ -z "$default" ]]; then
            echo "Error: No default scheme found!"
            exit 1
          fi

          echo $default > $GITHUB_WORKSPACE/default
          echo "Using default scheme: $default"

      - name: Debug Scheme
        run: |
          echo "Checking scheme value..."
          scheme=$(cat $GITHUB_WORKSPACE/default)
          if [[ -z "$scheme" ]]; then
            echo "Error: Scheme is empty!"
            exit 1
          fi
          echo "Using scheme: $scheme"

      - name: Debug Xcode Project
        working-directory: ios-assignment
        run: |
          echo "Checking for .xcworkspace or .xcodeproj..."
          ls -A | grep -i "\\.xcworkspace$" && echo "Found workspace" || echo "No workspace found"
          ls -A | grep -i "\\.xcodeproj$" && echo "Found project" || echo "No project found"

      - name: Debug Project Files
        working-directory: ios-assignment
        run: |
          echo "Listing project files:"
          ls -A

      - name: Boot iPhone 16 simulators with iOS 18.2
        run: |
          echo "Booting iPhone 16 simulators with OS 18.2..."
        
          # List all available iPhone 16 simulators with iOS 18.2 that are in 'Shutdown' state
          xcrun simctl list devices | grep -E 'iPhone 16 Pro' | grep '18.2' | grep 'Shutdown' | sed 's/^[ \t]*//;s/[ \t]*$//' | while read simulator; do
            echo "Booting simulator: $simulator"
        
            # Extract the device ID (UUID) for iPhone 16 simulators
            device_id=$(xcrun simctl list devices | grep "$simulator" | grep 'Shutdown' | sed -E 's/.*\(([A-Za-z0-9\-]+)\).*/\1/' | head -n 1)
            echo "device id: $device_id"
        
            # Check if device_id is empty or invalid
            if [[ -z "$device_id" ]]; then
              echo "Error: No valid device ID found for simulator: $simulator"
              continue
            fi
        
            # Attempt to boot the simulator
            echo "Attempting to boot simulator with ID: $device_id"
            xcrun simctl boot "$device_id"
      
            # Check if the boot status is 'Booted' or not
            MAX_RETRIES=5
            RETRY_COUNT=0
            while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
              boot_status=$(xcrun simctl list devices | grep "$device_id" | grep -o 'Booted')
              if [[ "$boot_status" == "Booted" ]]; then
                echo "Simulator $simulator is fully booted."
                break
              else
                echo "Simulator $simulator is still booting... Retrying..."
                RETRY_COUNT=$((RETRY_COUNT+1))
                sleep 10  # Wait for 10 seconds before retrying
              fi
            done
      
            if [[ $RETRY_COUNT -eq $MAX_RETRIES ]]; then
              echo "Error: Simulator $simulator failed to boot after $MAX_RETRIES attempts."
              continue
            fi
        
            # Proceed to the next simulator once this one is fully booted
            echo "Simulator $simulator booted successfully. Moving on to the next simulator..."
          done

      - name: List all available iPhone simulators with OS 18.2
        run: |
          echo "Listing all available iPhone simulators with OS 18.2..."
          
          # Show raw output for debugging purposes
          echo "Raw output of xcrun simctl list devices:"
          xcrun simctl list devices
          
          # Now filter for iPhone simulators with OS 18.2
          available_devices=$(xcrun simctl list devices | grep -E 'iPhone' | grep '18.2')
          
          if [[ -z "$available_devices" ]]; then
            echo "Error: No iPhone simulators found with OS 18.2!"
            exit 1
          fi
          
          echo "$available_devices"

      - name: Build
        working-directory: ios-assignment
        env:
          platform: iOS Simulator
        run: |
          scheme=$(cat $GITHUB_WORKSPACE/default)

          if [[ -z "$scheme" ]]; then
            echo "Error: Scheme is empty!"
            exit 1
          fi

          file_to_build=""
          if [[ -n "$(ls -A | grep -i \\.xcworkspace\$)" ]]; then
            filetype_parameter="workspace"
            file_to_build="$(ls -A | grep -i \\.xcworkspace\$)"
          elif [[ -n "$(ls -A | grep -i \\.xcodeproj\$)" ]]; then
            filetype_parameter="project"
            file_to_build="$(ls -A | grep -i \\.xcodeproj\$)"
          else
            echo "Error: No .xcworkspace or .xcodeproj found!"
            exit 1
          fi

          # Debug: List available iOS devices with OS 18.2 and exclude non-iOS devices like TV and Watch
          echo "Listing all available iOS 18.2 devices:"
          xcrun simctl list devices

          # Dynamically find the simulator ID for an available iPhone 16 (18.2) that is Booted or Shutdown
          SIMULATOR_ID=$(xcrun simctl list devices | grep -E 'iPhone 16.*18.2' | grep -E '(Booted|Shutdown)' | sed -E 's/.*\(([A-Za-z0-9\-]+)\).*/\1/' | head -n 1)

          # Debug: Print the simulator ID
          if [[ -z "$SIMULATOR_ID" ]]; then
            echo "Error: No matching iPhone 16 simulator with OS 18.2 found!"
            exit 1
          fi

          echo "Using simulator ID: $SIMULATOR_ID"

          # If the device is Shutdown, boot it
          SIMULATOR_STATE=$(xcrun simctl list devices | grep "$SIMULATOR_ID" | sed 's/.*(\(.*\)).*/\1/')
          if [[ "$SIMULATOR_STATE" == "Shutdown" ]]; then
            echo "Simulator is in Shutdown state. Attempting to boot the simulator..."
            xcrun simctl boot "$SIMULATOR_ID"
            sleep 15  # Allow time for the simulator to boot
          fi

          # Ensure simulator is booted
          SIMULATOR_STATE=$(xcrun simctl list devices | grep "$SIMULATOR_ID" | sed 's/.*(\(.*\)).*/\1/')
          if [[ "$SIMULATOR_STATE" != "Booted" ]]; then
            echo "Error: Simulator failed to boot up properly!"
            exit 1
          fi

          # Run xcodebuild using the dynamically fetched simulator ID
          echo "Building with simulator: iPhone 16 Pro Simulator (18.2)"
          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=iOS Simulator,id=$SIMULATOR_ID,OS=18.2"

      - name: Test
        env:
          platform: iOS Simulator
        run: |
          scheme=$(cat $GITHUB_WORKSPACE/default)

          if [[ -z "$scheme" ]]; then
            echo "Error: Scheme is empty!"
            exit 1
          fi

          file_to_build=""
          if [[ -n "$(ls -A | grep -i \\.xcworkspace\$)" ]]; then
            filetype_parameter="workspace"
            file_to_build="$(ls -A | grep -i \\.xcworkspace\$)"
          elif [[ -n "$(ls -A | grep -i \\.xcodeproj\$)" ]]; then
            filetype_parameter="project"
            file_to_build="$(ls -A | grep -i \\.xcodeproj\$)"
          else
            echo "Error: No .xcworkspace or .xcodeproj found!"
            exit 1
          fi

          echo "Testing with simulator: $SIMULATOR_DEVICE"
          xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$SIMULATOR_DEVICE"
